# Build-time helper invoked by add_custom_command in CMakeLists.txt.
# Computes the 8-char SHA1 prefix of routes.cpp and writes it as a constexpr
# string view into a generated header. Re-runs on every build where routes.cpp
# is newer than the header (CMake's add_custom_command DEPENDS handles that).
#
# Arguments (passed via -D on the cmake -P invocation):
#   ROUTES_SRC : absolute path to jurisdictions/nz_tenancy/routes.cpp
#   OUTPUT     : absolute path to the generated header
#
# The header is only rewritten when the hash actually changes — this prevents
# spurious main.cpp recompiles when routes.cpp is touched but its content
# fingerprint is identical (e.g. mtime-only changes).

if(NOT ROUTES_SRC)
    message(FATAL_ERROR "ROUTES_SRC not set")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "OUTPUT not set")
endif()

file(SHA1 "${ROUTES_SRC}" _routes_sha1)
string(SUBSTRING "${_routes_sha1}" 0 8 _routes_hash)

set(_new_content
"#pragma once
// Auto-generated by apps/nz_tenancy/generate_routes_hash.cmake.
// 8-char SHA1 prefix of jurisdictions/nz_tenancy/routes.cpp, recomputed on
// every build where routes.cpp changes. Matches eval_judge.py:_routes_hash
// so /healthz advertises a fingerprint the eval can correlate cache keys
// against.
namespace astraea {
inline constexpr const char* kRoutesHash = \"${_routes_hash}\";
} // namespace astraea
")

set(_write TRUE)
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _existing)
    if(_existing STREQUAL "${_new_content}")
        set(_write FALSE)
    endif()
endif()
if(_write)
    file(WRITE "${OUTPUT}" "${_new_content}")
endif()
